### ISSUE TITLE
properietary license

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_nacl_session#1]
What's the deal here?

https://github.com/Pylons/pyramid_nacl_session/blob/49e3a910de3638718f6f088751fb2835ba8d36ec/setup.py#L16

Also it appears the repo is missing CONTRIBUTORS.txt.

**Comment by tseaver** [comment]
The licenses is a copy-pasta error, fixed in dc180ec06579c5797f289ca0484ec10e5088765c.

I will add `CONTRIBUTORS.txt`.

**Comment by mmerickel** [comment]
The specific line I linked to is not fixed in that commit.

**Comment by mmerickel** [comment]
^ again, not fixed yet!

**Comment by tseaver** [comment]
Trove metadata was correct, but not the separate `license=` line.  1232fa7 fixes it.
