### ISSUE TITLE
Encrypt the mail address in .travis.yml to disable notifications from forks

### ISSUE THREAD

**Issue by lmctv** [Pylons/pyramid_nacl_session#10]
@tseaver @mmerickel  As suggested in travis-ci/travis-ci#1094 and implemented in pyca/cryptography#3193 , I think the email address in .travis.yml should be encrypted, by executing the command ``travis encrypt pyramid-checkins@lists.repoze.org`` and replacing the email address with the ``secure: ...`` output at

```
notifications:
  email:
    - pyramid-checkins@lists.repoze.org
```

**Comment by tseaver** [comment]
@lmctv I don't understand why you can't just Do the Right Thing and change your local `.travis.yml` to omit notifications (or send them to yourself, if you like).  `.travis.yml` is intrinsically about repository-local policies.

Encrypting the public mailling list address doesn't seem useful to me.

**Comment by lmctv** [comment]
Sorry, at first I'm apologyzing for the spam.

The RSA string encryption is the way travis suggests leaving stuff in .travis.yml which can is only accessible to the specific builder, which has the private key available when running.

While I concur with (many) others who would simply like to disable notifications from the travis account GUI, the problem with plain notifications inside .travis.yml is that you don't always look at the configuration file just after forking a repo.

Sorry once more.

**Comment by mmerickel** [comment]
Thanks for the suggested fix but I'd rather wait until travis allows a better option to fix this in their UI, decoupling the email from the yaml file. Until then it is what it is.
