### ISSUE TITLE
Update owners on PyPI

### ISSUE THREAD

**Issue by digitalresistor** [Pylons/pyramid_nacl_session#12]
Hey @tseaver,

Could you add one or more of the following people as an owner on the PyPI project:

- `xistence` - me, @bertjwregeer  
- `mmerickel` - @mmerickel 
- `pylonsbot` - release bot/continuance bot

Thank you,
Bert

**Comment by mmerickel** [comment]
@tseaver ping

**Comment by tseaver** [comment]
Done (I made the bot a maintainer, not an owner, FWIW).

**Comment by digitalresistor** [comment]
Thanks @tseaver!
