### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rouge8** [Pylons/pyramid_nacl_session#15]
There have been a lot of changes since the last release: https://github.com/Pylons/pyramid_nacl_session/compare/0.3...master I just spent half an hour or so trying to figure out why the package wasn't working like I expected based on GitHub until I realized it's all unreleased...

**Comment by mmerickel** [comment]
Yes I'll look at what's missing to cut a release.

**Comment by mmerickel** [comment]
Ok 1.0 is out.

**Comment by rouge8** [comment]
Thanks! I don't think RTD has gotten updated though...

**Comment by stevepiercy** [comment]
Thanks, I'm looking into it now. Looks like I got Maintainer rights on RTD now.

**Comment by stevepiercy** [comment]
I added a webhook to RTD for this repo. [Build successful](https://readthedocs.org/projects/pyramid-nacl-session/builds/11683462/).

Looks like we need to do a little housekeeping to update the version number, too. I got it.

**Comment by stevepiercy** [comment]
nm, it's just aggressive caching somewhere. https://docs.pylonsproject.org/projects/pyramid-nacl-session/en/latest/changes.html#id2
